sudo: required

language: go

env:
  global:
  - IMAGE_NAME=containerum/chkit
  - CONTAINERUM_HOME="~/.config/containerum"
  - CONTAINERUM_API="https://api.containerum.io"

services:
  - docker

install:
  - sudo mkdir -p ${CONTAINERUM_HOME}
  - echo ${KEY} | base64 -d > ${CONTAINERUM_HOME}/privkey.pem
  - echo ${PUB_KEY} | base64 -d > ${CONTAINERUM_HOME}/pubkey.pem

script:
  - make release
  - docker build -t "$IMAGE_NAME" .

before_deploy:
  - docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
  on:
    tags: true
