sudo: required

language: go

env:
  global:
  - IMAGE_NAME=containerum/chkit
  - CONTAINERUM_HOME="~/.config/containerum"
  - CONTAINERUM_API="https://api.containerum.io"

services:
  - docker

install:
  - sudo mkdir -p ${CONTAINERUM_HOME}
  - if [ "$TRAVIS_TAG" ]; then echo ${KEY} | base64 -d > ${CONTAINERUM_HOME}/privkey.pem; fi
  - if [ "$TRAVIS_TAG" ]; then echo ${PUB_KEY} | base64 -d > ${CONTAINERUM_HOME}/pubkey.pem; fi

script:
  - make release
  - docker build -t "$IMAGE_NAME" .

before_deploy:
  - docker login -u="$DOCKER_LOGIN" -p="$DOCKER_PASSWORD"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
  on:
    tags: true
- provider: releases
  api_key: $GITHUB_TOKEN
  file:
    - "build/chkit_linux_386_${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    tags: true
