[prune]
  go-tests = true
  unused-packages = true
  non-go = true

[[constraint]]
  name = "github.com/containerum/kube-client"
  version = "~0.23.12"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/olekukonko/tablewriter"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/urfave/cli.v2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.1.1"

[[constraint]]
  revision = "8152e7eb6ccf8679a64582a66b78519688d156ad"
  name = "github.com/inconshreveable/go-update"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "~1.0.1"

[[constraint]]
  name = "github.com/vbauerster/mpb"
  version = "~3.2.0"

[[constraint]]
  name = "git.containerum.net/ch/api-gateway"
  branch = "develop"
  
[[constraint]]
  branch = "develop"
  name = "git.containerum.net/ch/auth"

[[constraint]]
  branch = "develop"
  name = "git.containerum.net/ch/resource-service"

[[constraint]]
  branch = "develop"
  name = "git.containerum.net/ch/permissions"

[[constraint]]
  branch = "develop"
  name = "git.containerum.net/ch/kube-api"

[[constraint]]
  name = "github.com/octago/sflags"
  version = "~0.2.0"

[[constraint]]
  name = "github.com/oleiade/reflections"
  version = "~v1.0.0"

[[constraint]]
  name = "github.com/ninedraft/boxofstuff"
  version = "~v0.3.0"