
Name = "chkit-errors"
SID = 777

[[error]]
    Name = "UnableToInitClient"
    Message = "unable to init client"
    StatusHTTP = 418
    Kind = 1

[[error]]
    Name = "InvalidUsername"
    Message = "invalid username"
    StatusHTTP  = 418
    Kind = 2

[[error]]
    Name = "InvalidPassword"
    Message = "invalid password"
    StatusHTTP = 418
    Kind = 3

[[error]]
    Name = "UnableToReadUsername"
    Message = "unable to read username"
    StatusHTTP = 418
    Kind = 4

[[error]]
    Name = "UnableToReadPassword"
    Message = "unable to read password"
    StatusHTTP = 418
    Kind = 5

[[error]]
    Name = "UnableToSaveConfig"
    Message = "unable to save config"
    StatusHTTP = 418
    Kind = 6

